name: google_api_downloader

on:
  push:

  workflow_dispatch:

jobs:
  access_google_api:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Use your desired Python version

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Create credentials file
      run: |
        ## settings/secrets/actions 
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" > credentials.json

    - name: Run your script
      run: python Colab/downloader.py
      env:
        GOOGLE_APPLICATION_CREDENTIALS: credentials.json  # Set environment variable

  
