name: youtube_tools

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |          
          python -m pip install --upgrade pip
          pip install -r requirements.txt

          python -m nodejs


      - run : |
          #git clone https://github.com/YunzheZJU/youtube-po-token-generator.git  

          #npm install jsdom
          #node youtube-po-token-generator/examples/one-shot.js

          bash RUNNER.sh 


      - run : |
          python youtube_tools.py
          ls -la 




